### ISSUE TITLE
Samples/Downloader does not build on SDK 1.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hiteshsahu/apps-for-android#27]
```
What steps will reproduce the problem?

Checkout the source, create a build file and use ant to build.

What is the expected output? What do you see instead?

Expect build to be successful.

What version of the product are you using? On what operating system?

SDK 1.0 on Ubuntu Linux

Please provide any additional information below.

There are a few errors starting with:

DownloaderActivity.java:24: cannot find symbol
    [javac] symbol  : class AndroidHttpClient
    [javac] location: package android.net.http
    [javac] import android.net.http.AndroidHttpClient;

I guess this is to do with the recent changes in the SDK as I can't find 
android.net.http.AndroidHttpClient in the docs for the SDK. The OpenGL ES
examples built fine and are very useful.



```

Original issue reported on code.google.com by `djbj...@googlemail.com` on 21 Oct 2008 at 3:45

**Comment by GoogleCodeExporter** [comment]
Original comment by `morri...@gmail.com` on 13 Nov 2008 at 10:18
- Added labels: **Application-Samples**

**Comment by GoogleCodeExporter** [comment]
Original comment by `morri...@gmail.com` on 13 Nov 2008 at 10:19

**Comment by GoogleCodeExporter** [comment]
Original comment by `morri...@gmail.com` on 13 Nov 2008 at 10:21
- Changed state: **Accepted**
